### PR TITLE
Fix PHP notice

### LINKED ISSUE #47: Fix PHP notice
PHP Notice
```<b>Notice</b>:  Function register_rest_route was called incorrectly. The REST API route definition for tour/v1/save-progress is missing the required permission_callback argument. For REST API routes that are intended to be public, use __return_true as the permission callback. Please see <a>Debugging in WordPress</a> for more information. (This message was added in version 5.5.0.) in <b>/Users/alex/Sites/localhost/wp/wp-includes/functions.php</b> on line <b>6031</b><br />```

### PR DESCRIPTION
**Pull request by trymebytes**
Fixes #47 by adding `permission_callback`

### CODE REVIEW

File: class-tour.php [hunk 1]
```diff
@@ -151,15 +151,18 @@ public static function rest_api_init() {
 						'success' => true,
 					);
 				},
+				'permission_callback' => function () {
+					return is_user_logged_in();
+				},
```
Comment (akirk) [inline class-tour.php]: If you just wrap a function it can be done like this:
```suggestion
				'permission_callback' => 'is_user_logged_in',
```

**Review by akirk — APPROVED** [review]
Great, thanks!

File: class-tour.php (hunk 1 above)
Comment (trymebytes) [reply class-tour.php]: Thank you!
